### ISSUE TITLE
Text indentation | Отступы

### ISSUE THREAD

**Issue by phobos2077** [Ytfarc/sfall2#1]
Why don't use tabs for indentation like in the original project?
It's harder to read the code and a little bit annoying when merging code.

Почему бы не использовать табы для отступов?
Когда один пробел - сложнее читать код и мерджить.

(Альтернатива - 4 пробела, если не устраивают табы)

**Comment by Ytfarc** [comment]
Так редактор втроенный в FAR, видимо меняет таб на пробел. А 4 пробела вбивать для каждой строки лень.

**Comment by phobos2077** [comment]
Я так и подумал. Вбивать вручную ничего не нужно, просто открой код в любой нормальной IDE (например Visual Studio), там есть функция авто-форматирования. Чем я собственно и пользуюсь, когда "ворую" куски твоего кода :)
Один пробел режет глаз, все используют от 2 до 8 пробелов либо табы, хотя 4 пробела самый популярный вариант. В нашей версии пока используются табы.
