### ISSUE TITLE
Engine offsets in Define.h | Смещения движка в Define.H

### ISSUE THREAD

**Issue by phobos2077** [Ytfarc/sfall2#2]
Почему бы не перенести адреса переменных движка из Define.h в FalloutEngine.h, который для этого был предназначен?
Насколько я понимаю, в Define.H мы кладем только всякие константы, вроде типов предметов и прочего.

**Comment by Ytfarc** [comment]
Твоя правда ;) Сначала ради теста прописал один адрес переменной, а потом уже на автомате начал добавлять новые.
