### ISSUE TITLE
"Hook" functions naming | Именование "Хуков"

### ISSUE THREAD

**Issue by phobos2077** [Ytfarc/sfall2#3]
Есть предложение использовать слово hook в названии функций, встраивающих новый код в движок, только для тех случаев когда происходит глобальная подмена вызова некоторой функции. Пример:

```
    // Fix for "Too Many Items Bug"
HookCall(0x4A596A, &scr_save_hook);
HookCall(0x4A59C1, &scr_save_hook);
```

В данном случае код заменяет все вызовы функции _scr_write_ScriptNode__ на _scr_save_hook_. Название _scr_write_ScriptNode_hook_ дало бы лучшее понимание, как используется эта функция.

В тех же случаях, когда код просто встраивается внутрь некоторой функции движка, например тут:

```
// Fixes for clickability issues in PipBoy 
MakeCall(0x4971C7, &pipboy_hook, false);
MakeCall(0x499530, &PipAlarm_hook, false);
```

Предлагаю использовать суффикс _hack_, то есть _pipboy_hack_ и _PipAlarm_hack_. Таким образом будет легче поиском по коду разобраться, где подмена функции а где просто изменение её поведения.

Есть еще третий случай, когда происходит подмена вызовов, но не всех, а только в определенном методе (локально). Пример:

```
    // Fix crash when using stimpak on a victim and then exiting the map
HookCall(0x4A27E7, &queue_clear_type_hook);
```

В данном случае подменяется функция _mem_free_()_, но только лишь в одном месте. В таком случае можно обозвать функцию как _queue_clear_type_mem_free_hook_ либо названием, более конкретно описывающем её задачу.

**Comment by Ytfarc** [comment]
Хлопотно и лень :-p

**Comment by phobos2077** [comment]
Для нового кода не должно быть хлопотно.
