### ISSUE TITLE
Dodgy doors and missed ranged attacks

### ISSUE THREAD

**Issue by NovaRain** [Ytfarc/sfall2#4]
Currently it seems the dodgy door fix only works for melee/unarmed. With the fix, any missed melee/unarmed attack against a door will play the attack animation correctly. But for ranged attacks, any missed shot to a closed door will make it open. It doesn't seem right to me. Maybe you can check it?

**Comment by Ytfarc** [comment]
Ok, I will check it a bit later

**Comment by Ytfarc** [comment]
Done (though I didn't test) ;)
