### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Lichtenshtein** [Ytfarc/sfall2#5]
Извините, не нашёл как связаться с вами по-другому. Будет ли обновление до актуальной версии sfall? Есть ли где-нибудь уже скомпелированная версия sfall2?

**Comment by Ytfarc** [comment]
https://www.dropbox.com/s/g3uxjd4obb3s1dp/sfall2.7z?dl=0
Последняя версия, включающая исправления взрывчатки (без упоминания в ченжлоге).

**Comment by Ytfarc** [comment]
Пожалуй лучше дать ссылку на тему: http://fforum.kochegarov.com/index.php?showtopic=29288

**Comment by Lichtenshtein** [comment]
Спасибо. :) Сам случайно потом эту тему нашёл.
